### ISSUE TITLE
Log token position for all errors

### ISSUE THREAD

**Issue by chiefy** [fatih/hcl#6]
I am trying to create a Sublime Text 3 linter using `hclfmt` but it seems like [not all errors get logged with token position](https://github.com/fatih/hcl/blob/master/parser/parser.go#L169). Any reason the parser doesn't have a `err` function/method like the [scanner does](https://github.com/fatih/hcl/blob/master/scanner/scanner.go#L481-L491)?

**Comment by fatih** [comment]
Hi @chiefy This is moved to hashicorp/hcl. Checkout my blog post about the move: https://medium.com/@farslan/hcl-parser-family-in-pure-go-86589a5648fb Please test that version. Also hclfmt is updated, just `go get -u` it again and it'll use the new hcl package. Thanks
